READY = 'READY'
PRESENCE_UPDATE = 'PRESENCE_UPDATE'

MESSAGE_CREATE = 'MESSAGE_CREATE'
MESSAGE_UPDATE = 'MESSAGE_UPDATE'

CHANNEL_CREATE = 'CHANNEL_CREATE'
CHANNEL_UPDATE = 'CHANNEL_UPDATE'
CHANNEL_DELETE = 'CHANNEL_DELETE'

GUILD_CREATE = 'GUILD_CREATE'
GUILD_DELETE = 'GUILD_DELETE'

TYPING_START = 'TYPING_START'
TYPING_STOP = 'TYPING_STOP'
